### PR TITLE
Add a Makefile, to be used with BinaryBuilder

### PR DESCRIPTION
**Pull request by giordano**
To be fair, such a simple program doesn't need a `Makefile`, but this might be useful to illustrate some of the details of building a library/program with BinaryBuilder

### CODE REVIEW

**Comment by jakubwro** [comment]
> To be fair, such a simple program doesn't need a `Makefile`, but this might be useful to illustrate some of the details of building a library/program with BinaryBuilder

Thanks! I think makefile is needed, the script I used so far does not look very good. I was a bit stuck cause the only Julia version that BinaryBuilder.jl is working for me (macOS) is 1.3.0 so I had to downgrade. Now I have everything set up, will work on the tutorial tomorrow.

**Comment by giordano** [comment]
> I was a bit stuck cause the only Julia version that BinaryBuilder.jl is working for me (macOS) is 1.3.0

What problem did you have?

**Comment by jakubwro** [comment]
> > I was a bit stuck cause the only Julia version that BinaryBuilder.jl is working for me (macOS) is 1.3.0
> 
> What problem did you have?

On 1.3.1 there is problem with hash calculation (there is open issue for that). Cannot reproduce now, cause I replaced it with 1.3.0.

On 1.5.0:
```
> /Applications/Julia-1.5.app/Contents/Resources/julia/bin/julia make_tarballs.jl
ERROR: LoadError: LoadError: LoadError: UndefVarError: Compress not defined
Stacktrace:
 [1] include(::Module, ::String) at ./Base.jl:377
 [2] include(::String) at /Users/jakub/.julia/packages/Registrator/d91HE/src/regedit/RegEdit.jl:1
 [3] top-level scope at /Users/jakub/.julia/packages/Registrator/d91HE/src/regedit/RegEdit.jl:15
 [4] include(::Module, ::String) at ./Base.jl:377
 [5] include(::String) at /Users/jakub/.julia/packages/Registrator/d91HE/src/Registrator.jl:1
 [6] top-level scope at /Users/jakub/.julia/packages/Registrator/d91HE/src/Registrator.jl:11
 [7] include(::Module, ::String) at ./Base.jl:377
 [8] top-level scope at none:2
 [9] eval at ./boot.jl:331 [inlined]
 [10] eval(::Expr) at ./client.jl:449
 [11] top-level scope at ./none:3
in expression starting at /Users/jakub/.julia/packages/Registrator/d91HE/src/regedit/register.jl:195
in expression starting at /Users/jakub/.julia/packages/Registrator/d91HE/src/regedit/RegEdit.jl:15
in expression starting at /Users/jakub/.julia/packages/Registrator/d91HE/src/Registrator.jl:11
ERROR: LoadError: LoadError: Failed to precompile Registrator [4418983a-e44d-11e8-3aec-9789530b3b3e] to /Users/jakub/.julia/compiled/v1.5/Registrator/Obz5J_eVgZw.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1270
 [3] _require(::Base.PkgId) at ./loading.jl:1029
 [4] require(::Base.PkgId) at ./loading.jl:927
 [5] require(::Module, ::Symbol) at ./loading.jl:922
 [6] include(::Module, ::String) at ./Base.jl:377
 [7] include(::String) at /Users/jakub/.julia/packages/BinaryBuilder/4sWut/src/BinaryBuilder.jl:4
 [8] top-level scope at /Users/jakub/.julia/packages/BinaryBuilder/4sWut/src/BinaryBuilder.jl:29
 [9] include(::Module, ::String) at ./Base.jl:377
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:331 [inlined]
 [12] eval(::Expr) at ./client.jl:449
 [13] top-level scope at ./none:3
in expression starting at /Users/jakub/.julia/packages/BinaryBuilder/4sWut/src/AutoBuild.jl:5
in expression starting at /Users/jakub/.julia/packages/BinaryBuilder/4sWut/src/BinaryBuilder.jl:29
ERROR: LoadError: Failed to precompile BinaryBuilder [12aac903-9f7c-5d81-afc2-d9565ea332ae] to /Users/jakub/.julia/compiled/v1.5/BinaryBuilder/WHzgM_eVgZw.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1270
 [3] _require(::Base.PkgId) at ./loading.jl:1029
 [4] require(::Base.PkgId) at ./loading.jl:927
 [5] require(::Module, ::Symbol) at ./loading.jl:922
 [6] include(::Module, ::String) at ./Base.jl:377
 [7] exec_options(::Base.JLOptions) at ./client.jl:288
 [8] _start() at ./client.jl:484
```

On 1.4.0:

```
ERROR: LoadError: LoadError: Failed to precompile Registrator [4418983a-e44d-11e8-3aec-9789530b3b3e] to /Users/jakub/.julia/compiled/v1.5/Registrator/Obz5J_eVgZw.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1270
 [3] _require(::Base.PkgId) at ./loading.jl:1029
 [4] require(::Base.PkgId) at ./loading.jl:927
 [5] require(::Module, ::Symbol) at ./loading.jl:922
 [6] include(::Module, ::String) at ./Base.jl:377
 [7] include(::String) at /Users/jakub/.julia/packages/BinaryBuilder/4sWut/src/BinaryBuilder.jl:4
 [8] top-level scope at /Users/jakub/.julia/packages/BinaryBuilder/4sWut/src/BinaryBuilder.jl:29
 [9] include(::Module, ::String) at ./Base.jl:377
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:331 [inlined]
 [12] eval(::Expr) at ./client.jl:449
 [13] top-level scope at ./none:3
in expression starting at /Users/jakub/.julia/packages/BinaryBuilder/4sWut/src/AutoBuild.jl:5
in expression starting at /Users/jakub/.julia/packages/BinaryBuilder/4sWut/src/BinaryBuilder.jl:29
ERROR: LoadError: Failed to precompile BinaryBuilder [12aac903-9f7c-5d81-afc2-d9565ea332ae] to /Users/jakub/.julia/compiled/v1.5/BinaryBuilder/WHzgM_eVgZw.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1270
 [3] _require(::Base.PkgId) at ./loading.jl:1029
 [4] require(::Base.PkgId) at ./loading.jl:927
 [5] require(::Module, ::Symbol) at ./loading.jl:922
 [6] include(::Module, ::String) at ./Base.jl:377
 [7] exec_options(::Base.JLOptions) at ./client.jl:288
 [8] _start() at ./client.jl:484
in expression starting at /Users/jakub/Projects/sinewave/binbuild/make_tarballs.jl:3
> /Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia make_tarballs.jl
ERROR: LoadError: LoadError: UndefVarError: stdlib not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./Base.jl:26
 [2] top-level scope at /Users/jakub/.julia/packages/RegistryTools/j44Yl/src/builtin_pkgs.jl:1
 [3] include(::Module, ::String) at ./Base.jl:377
 [4] include(::String) at /Users/jakub/.julia/packages/RegistryTools/j44Yl/src/RegistryTools.jl:1
 [5] top-level scope at /Users/jakub/.julia/packages/RegistryTools/j44Yl/src/RegistryTools.jl:14
 [6] include(::Module, ::String) at ./Base.jl:377
 [7] top-level scope at none:2
 [8] eval at ./boot.jl:331 [inlined]
 [9] eval(::Expr) at ./client.jl:449
 [10] top-level scope at ./none:3
in expression starting at /Users/jakub/.julia/packages/RegistryTools/j44Yl/src/builtin_pkgs.jl:1
in expression starting at /Users/jakub/.julia/packages/RegistryTools/j44Yl/src/RegistryTools.jl:14
ERROR: LoadError: LoadError: Failed to precompile RegistryTools [d1eb7eb1-105f-429d-abf5-b0f65cb9e2c4] to /Users/jakub/.julia/compiled/v1.4/RegistryTools/omWip_R3bHV.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1270
 [3] _require(::Base.PkgId) at ./loading.jl:1029
 [4] require(::Base.PkgId) at ./loading.jl:927
 [5] require(::Module, ::Symbol) at ./loading.jl:922
 [6] include(::Module, ::String) at ./Base.jl:377
 [7] include(::String) at /Users/jakub/.julia/packages/BinaryBuilder/4sWut/src/BinaryBuilder.jl:4
 [8] top-level scope at /Users/jakub/.julia/packages/BinaryBuilder/4sWut/src/BinaryBuilder.jl:29
 [9] include(::Module, ::String) at ./Base.jl:377
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:331 [inlined]
 [12] eval(::Expr) at ./client.jl:449
 [13] top-level scope at ./none:3
in expression starting at /Users/jakub/.julia/packages/BinaryBuilder/4sWut/src/AutoBuild.jl:5
in expression starting at /Users/jakub/.julia/packages/BinaryBuilder/4sWut/src/BinaryBuilder.jl:29
ERROR: LoadError: Failed to precompile BinaryBuilder [12aac903-9f7c-5d81-afc2-d9565ea332ae] to /Users/jakub/.julia/compiled/v1.4/BinaryBuilder/WHzgM_R3bHV.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1270
 [3] _require(::Base.PkgId) at ./loading.jl:1029
 [4] require(::Base.PkgId) at ./loading.jl:927
 [5] require(::Module, ::Symbol) at ./loading.jl:922
 [6] include(::Module, ::String) at ./Base.jl:377
 [7] exec_options(::Base.JLOptions) at ./client.jl:288
 [8] _start() at ./client.jl:484
in expression starting at /Users/jakub/Projects/sinewave/binbuild/make_tarballs.jl:3
```


And my script is:

```julia
# Note that this script can accept some limited command-line arguments, run
# `julia build_tarballs.jl --help` to see a usage message.
using BinaryBuilder, Pkg

name = "sinewave"
version = v"0.0.1"

# Collection of sources required to complete build
sources = [
    "https://github.com/jakubwro/sinewave.git" =>
    "7d7fbe557d226ad5742862107e764c753f027df3",
]

# Bash recipe for building across all platforms

script = raw"""

cd $WORKSPACE/srcdir
cd sinewave/

if [ $target = "x86_64-apple-darwin14" ]; then
    gcc -dynamiclib sinewave.c -o libsinewave.dylib -std=gnu99 -c
elif [ $target = "x86_64-w64-mingw32" ]; then
    gcc -shared -o libsinewave.dll sinewave.o
else # linux
    gcc -c sinewave.c -fpic -std=gnu99 -Wall
    gcc -shared -o libsinewave.so sinewave.o
fi

mkdir ${libdir}
cp libsinewave.* ${libdir}

"""

# These are the platforms we will build for by default, unless further
# platforms are passed in on the command line
platforms = supported_platforms()

# The products that we will ensure are always built
products = [
    LibraryProduct("libsinewave", :libsinewave)
]

# Dependencies that must be installed before this package can be built
dependencies = [

]

# Build the tarballs, and possibly a `build.jl` as well.
build_tarballs(ARGS, name, version, sources, script, platforms, products, dependencies)
```

**Comment by giordano** [comment]
What version of BinaryBuilder are you using?  Uh, I just noted that fixes for Julia v1.4 and v1.5 are in `master`, but not in any stable release.

**Comment by jakubwro** [comment]
> > I was a bit stuck cause the only Julia version that BinaryBuilder.jl is working for me (macOS) is 1.3.0
> 
> What problem did you have?



> What version of BinaryBuilder are you using? Uh, I just noted that fixes for Julia v1.4 and v1.5 are in `master`, but not in any stable release.

I use version 0.2.2 everywhere.
I tried also on julia 1.2.0, but there is only very old one without docker support, only qemu.


```
(@v1.5) pkg> status
Status `~/.julia/environments/v1.5/Project.toml`
  [6e4b80f9] BenchmarkTools v0.4.3
  [12aac903] BinaryBuilder v0.2.2
  [4418983a] Registrator v1.0.0
```

**Pull request merged**
